### ISSUE TITLE
Taller de Flutter

### ISSUE THREAD

**Issue by LisoProgrammer** [ISCOUTB/DG-Fasturno#1]

**Comment by LisoProgrammer** [comment]
Realicé la instalación de el SDK de Flutter.
![Image](https://github.com/user-attachments/assets/a7806952-8036-4c4a-bdbd-b5b7049a269c)
Videos vistos:
https://youtu.be/7N-wDxe18PA?si=N7j7-tqWTkqoUC61
https://youtu.be/3N8MMvLBxss?si=mj09YTiA589ZwGsh
https://youtu.be/1z6YP7YmvwA?si=zq_dBZ3nKCaNB-Ok

**Comment by Jorge-M29** [comment]
Aprendiendo lenguaje de Dart, realice la instalación del SDK de flutter y su instalación en VS Code

**Comment by HKevinGuerrero** [comment]
![Image](https://github.com/user-attachments/assets/da3856f5-dd05-42fe-95d0-3b4de9cafd8c)

Descargué Android studio para simular un movil, como se veria nuestro proyecto ahi plasmado

**Comment by Javimercadobolivar** [comment]
![IMG-20240909-WA0032](https://github.com/user-attachments/assets/8c4370b4-62d9-40fd-9e70-464c66e8a8d1)
 Realicé la instalación de flutter en vs code, falta la instalación de Android Studio.

**Comment by jairoserrano** [comment]
Ok adelante.
