### ISSUE TITLE
Maquetar y programar interacción del layout principal

### ISSUE THREAD

**Issue by LisoProgrammer** [ISCOUTB/DG-Fasturno#11]
- [x] Maquetar encabezado o header de la app.
- [x] Programar interacción con el menú de ajustes (abrir y cerrar).
- [x] Maquetar ventana de crear turno nuevo.
- [x] Programar la interacción con el botón para crear turnos (+), abrir ventana.

**Comment by LisoProgrammer** [comment]
Se maquetó el encabezado, el menú de opciones y su interacción.
![Image](https://github.com/user-attachments/assets/8b7fb27e-187d-482a-a9ea-c7d4c1014c4b)
![Image](https://github.com/user-attachments/assets/794d52a1-3dc0-4523-931b-74cd60626a46)

**Comment by LisoProgrammer** [comment]
![Image](https://github.com/user-attachments/assets/c3d05f23-7c54-4107-97c8-19315084afaf)

**Comment by jairoserrano** [comment]
Adelante
