### ISSUE TITLE
Construcción del Backend

### ISSUE THREAD

**Issue by LisoProgrammer** [ISCOUTB/DG-Fasturno#2]

**Comment by Jorge-M29** [comment]
Propongo usar Firebase como conexión para la base de datos, porque es más sencilla y viene de los creadores del Flutter, donde dan diversas herramientas como puede ser de autenticación y verificación por ejemplo.

Link: https://firebase.google.com/?hl=es

**Comment by HKevinGuerrero** [comment]
Propongo hacer un estudio profundo de la documentacion brindada en google sobre Flutter
Link: https://docs.flutter.dev/

**Comment by LisoProgrammer** [comment]
Falta realizar un análisis de requerimientos para la API propuesta. Que propósito tiene la API, que datos recibirá y cual será la respuesta dependiendo del procesamiento de los datos recibidos.

**Comment by LisoProgrammer** [comment]
La API que se va a utilizar tiene como propósito enviar correos electrónicos a los clientes cuando ya son sus turnos. Recibirá como datos el correo electrónico del cliente, el nombre del cliente y la hora del turno. Enviará un correo electrónico con asunto "Ya es tu turno. El barbero te está esperando...", el cuerpo del mensaje estárá estructurado de esta forma:

Hola, [Nombre del Cliente],

Ya es tu turno para el servicio en la barbería. Por favor, preséntate en la barbería a las [Hora] de hoy. Por favor no demores.

Atentamente,
Fasturno.

Te esperamos.

**Comment by jairoserrano** [comment]
van a usar es flutter y una api sencilla. no firebase
