### ISSUE TITLE
Insertar turno nuevo

### ISSUE THREAD

**Issue by LisoProgrammer** [ISCOUTB/DG-Fasturno#28]
- [x] Crear una función que se encargue de insertar en el layout el modelo de tarjeta de turno con todos sus datos.
- [x] Almacenar el turno creado.
- [x] Leer los turnos creados.

**Comment by HKevinGuerrero** [comment]
Con el commit recien subido, se hicieron esas tareas asignadas. Solamente falta confirmar que funcione en emuladores ya que mi computador y el de nuestro equipo no soporta emuladores de ningun tipo. Pero teniendo en cuenta varios videos e investigaciones ya deberia hacer lo pedido

**Comment by LisoProgrammer** [comment]
Confirmo el funcionamiento en entorno Windows y Android. 
Windows:
![Image](https://github.com/user-attachments/assets/96174832-dbb0-40cb-bff3-e02400b5af80)
Android:
![Image](https://github.com/user-attachments/assets/ffed4985-fd10-40a5-9a7f-41c38a963487)
