### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by LisoProgrammer** [ISCOUTB/DG-Fasturno#3]
Diseñar las views de la aplicación.

**Comment by LisoProgrammer** [comment]
Wireframes Figma: https://www.figma.com/proto/qVnPpRrLwYEWWqY4s8YTN1/fasturno?node-id=14-2&node-type=CANVAS&t=8di64znUVwAPHMI9-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1

**Comment by jairoserrano** [comment]
Faltaría la versión web.

**Comment by LisoProgrammer** [comment]
Se realizó una reestructuración del enfoque de la aplicación, teniendo en cuenta la información compartida por el profesor. Dicha información sugiere hacer una app autocontenida, basado en esto, el enfoque de la aplicación cambia de tener interfaz de inicio de sesión, registro de usuarios, y todo lo relacionado con estos, a solo un usuario que será el barbero y una interfaz de cola para turnos con ciertos ajustes y acciones que puede realizar el barbero. Además se piensa en utilizar solo una API que envíe correos electrónicos a los clientes cuando ya son sus turnos.

**Diseños.**

**app**
![Image](https://github.com/user-attachments/assets/778f0214-4f2d-4538-af4a-a875a716a852)
![Image](https://github.com/user-attachments/assets/27cf40eb-114d-4437-a1b1-c90de50bb496)

**web**
![Image](https://github.com/user-attachments/assets/f6c88015-1e21-4cf4-aa35-8637ac66abad)
![Image](https://github.com/user-attachments/assets/b8be0532-9117-43a8-9ab0-0f5587e57a4e)

**Comment by HKevinGuerrero** [comment]
Con este cambio de enfoque se puede agilizar la construcción del proyecto, ya que resulta más complejo realizar un sistema multiusuario. En este sentido, la asignación de turnos sería más rápida, pues dicha asignación recae en un solo usuario (el barbero), simplificando el proceso de desarrollo.

**Comment by Javimercadobolivar** [comment]
Una de las ventajas de este cambio de idea para el proyecto es que el desarrollo de la aplicación y la web nos tomará menos tiempo. En cambio, con la idea anterior, nos dimos cuenta de que era demasiado extensa y no lograríamos completarla dentro del plazo previsto.

**Comment by Jorge-M29** [comment]
En el contexto de nuestro proyecto, es fundamental considerar la eficiencia en el desarrollo y la experiencia del usuario. Tras analizar nuestras propuestas, hemos llegado a la conclusión de que simplificar el enfoque puede ser altamente beneficioso.

**Comment by jairoserrano** [comment]
adelante
